language: csharp
mono: none
dotnet: 2.0.0
services: 
    - mongodb
    - docker

os: linux
dist: trusty
group: edge #enable sudo

script:
    - cd ../src/Obsidian
    - docker build -t za-pt/obsidian .