sudo: required
dist: trusty
language: csharp
solution: Obsidian.sln
mono: none
dotnet: 1.0.1
services: mongodb


before_install:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
    - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
    - sudo apt-get update
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
    - nvm install node
    # Repo for Yarn
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn        
install:
    - sudo apt-get install -y dotnet-dev-1.0.1

before_script:
    - dotnet restore
    - cd ./src/
    - cd ./Obsidian/
    - yarn

script:
    - dotnet build
    - cd ../../
    - chmod +x ./test.sh
    - ./test.sh
