language: csharp
mono: none

os: linux
dist: trusty
sudo: required


before_install:
    # MongoDB
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
    - echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
    # .NET Core
    - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
    # Yarn
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update
install:
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
    - nvm install node
    - sudo apt-get install -y yarn dotnet-dev-1.0.1 mongodb-org

before_script:
    - sudo service mongod restart
    - sleep 15
    - mongo mydb_test --eval 'db.test.insertOne({data:"test"});'
    - chmod +x ./*.sh
    - ./restore_packages.sh

script:
    - cd ./src/Obsidian
    - dotnet build
    - cd ../..
    - ./test.sh
    - cd ./src/Obsidian
    - npm run test:cover:travis
