sudo: required
dist: trusty

before_install:
    - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
    - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
    - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    - sudo apt-get update
        
install:
    - sudo apt-get install -y dotnet-dev-1.0.0-preview2-003121 mongodb-org

before_script:
    - sudo service mongod start
    - cd ./src/
    - dotnet restore
    - cd ./Obsidian/
    - npm update
    - node_modules/.bin/webpack

script:
    - dotnet --verbose build
    - cd ../../
    - chmod +x ./test.sh
    - ./test.sh