jobs:
  include:
    - stage: build and test
      language: csharp
      mono: none
      dotnet: 2.0.0
      services: mongodb
      os: linux
      dist: trusty
      group: edge
      script:
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
        - nvm install node
        - sudo apt-get install -y yarn
        - dotnet restore
        - cd ./src/Obsidian/
        - dotnet build
        - cd ../../test
        - for d in ./*/ ; do(cd "$d" && dotnet test); done
        - cd ../src/Obsidian
        - npm run test:cover:travis
        

    - stage: docker
      services: docker
      group: edge
      script: docker build -t za-pt/obsidian .
