language: csharp
mono: none
dotnet: 2.0.0
services: 
    - mongodb
    - docker

os: linux
dist: trusty
group: edge #enable sudo

jobs:
    include:
        - stage: build and test
            script: sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
            script: echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            script: sudo apt-get update
            script: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
            script: nvm install node
            script: sudo apt-get install -y yarn
            script: dotnet restore
            script: cd ./src/Obsidian/
            script: dotnet build
            script: cd ../../test
            script: for d in ./*/ ; do(cd "$d" && dotnet test); done
            script: cd ../src/Obsidian
            script: npm run test:cover:travis
        

        - stage: docker
            script: docker build -t za-pt/obsidian .