sudo: required
dist: trusty
language: csharp
solution: Obsidian.sln
mono: none
dotnet: 1.0.1
services: mongodb


before_install:
    # Repo for Yarn
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq 
install:
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
    - nvm install node
    - sudo apt-get install -y -qq yarn

before_script:
    - chmod +x ./*.sh
    - ./restore_packages.sh

script:
    - dotnet build
    - cd ../../
    - ./test.sh
