language: csharp
mono: none
dotnet: 2.0.0
services: 
    - mongodb
    - docker

os: linux
dist: trusty
group: edge #enable sudo

before_install:
    # Yarn
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

    - sudo apt-get update

install:
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
    - nvm install node
    - sudo apt-get install -y yarn

before_script:
    - dotnet restore
    - cd ./src/Obsidian/
    - yarn

script:
    - dotnet build
    - cd ../../test
    - for d in ./*/ ; do(cd "$d" && dotnet test); done
    - cd ../src/Obsidian
    - npm run test:cover:travis
    - docker build -t ZA-PT/Obsidian .