sudo: required
dist: trusty

before_install:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
    - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
    - echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
    - sudo apt-get update
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
    - nvm install node
    # Repo for Yarn
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn        
install:
    - sudo apt-get install -y dotnet-dev-1.0.1 mongodb-org

before_script:
    - sudo service mongod start
    - dotnet restore
    - cd ./src/
    - cd ./Obsidian/
    - npm install -g npm
    - yarn

script:
    - dotnet build
    - cd ../../
    - chmod +x ./test.sh
    - ./test.sh
