export const styles={
    userCard:{
        width:'400px',
        background:'#EEE',
        height:'200px',
        textAlign:'center',
        color:'black',
        verticalAlign:'center'
    },
    portalIndex:{
        margin:'30px'  
    },
    comboBox:{
        marginRight:'30px'
    },
    comboList:{
        paddingTop:"16px"
    }
}